### ISSUE TITLE
Exception: OperationException(linkException: ResponseFormatException(originalException: FormatException: Unexpected character (at character 1)

### ISSUE THREAD

**Issue by rrifafauzikomara** [zino-hofmann/graphql-flutter#1350]
logs

```dart
flutter: Request : {
  "userId": "244648"
}

flutter: Listen Subscription: Active

flutter: Listen Subscription Exception: OperationException(linkException: ResponseFormatException(originalException: FormatException: Unexpected character (at character 1)
Bad Request
^
, originalStackTrace: #0      _ChunkedJsonParser.fail (dart:convert-patch/convert_patch.dart:1383:5)
#1      _ChunkedJsonParser.parseNumber (dart:convert-patch/convert_patch.dart:1250:9)
#2      _ChunkedJsonParser.parse (dart:convert-patch/convert_patch.dart:915:22)
#3      _parseJson (dart:convert-patch/convert_patch.dart:35:10)
#4      JsonDecoder.convert (dart:convert/json.dart:610:36)
#5      JsonCodec.decode (dart:convert/json.dart:216:41)
#6      HttpLink._defaultHttpResponseDecoder (package:gql_http_link/src/link.dart:48:12)
#7      HttpLink._parseHttpResponse (package:gql_http_link/src/link.dart:117:53)
#8      HttpLink.request (package:gql_http_link/src/link.dart:78:28)
<asynchronous suspension>
), graphqlErrors: [])

flutter: Listen Subscription Data: {}

flutter: Listen Subscription Done
```

example code of subs
```dart
void _onErrorSubscription(Object error, StackTrace stackTrace) {
  print('Listen Subscription Error: $error & $stackTrace');
}

void _onDoneSubscription() {
  print('Listen Subscription Done');
}

void _subs() {
final baseUrl = Config.baseUrl + endPoint;
      final HttpLink link = HttpLink(baseUrl);

      Map<String, String> authHeader = {};
      authHeader['host'] = 'HOST';
      final encodedHeader = toBase64(authHeader);
      final WebSocketLink wsLink = WebSocketLink(
        ApiEndpoint.webSocket(encodedHeader),
        config: const SocketClientConfig(
          autoReconnect: true,
          inactivityTimeout: Duration(seconds: 60),
        ),
        subProtocol: GraphQLProtocol.graphqlWs,
      );

      final Link linkSplitted = link.split(
        (request) => request.isSubscription,
        wsLink,
        link,
      );

      final client = GraphQLClient(
        link: linkSplitted,
        cache: GraphQLCache(),
        alwaysRebroadcast: true,
      );

      final prettyStringRequest =
          const JsonEncoder.withIndent('  ').convert(options.variables);
      print('Request : $prettyStringRequest\n');

      final result = client.subscribe(options);
      Map<String, dynamic> data = {};
      result.listen(
        (event) {
          print('Listen Subscription: Active');
          if (event.hasException) {
            print(
              'Listen Subscription Exception: ${event.exception.toString()}',
            );
          }
          data = event.data ?? {};
          print('Listen Subscription Data: $data');
        },
        onDone: _onDoneSubscription,
        onError: _onErrorSubscription,
        cancelOnError: true,
      );
}
```

**Comment by robertoestivill** [comment]
You server is returning `Bad Request` and the library can not parse it.
Not a library problem if you are not constructing a proper request.

**Comment by rrifafauzikomara** [comment]
Hi @robertoestivill @vincenzopalazzo do u have any example of subs implementation? seems ur documentation not proper yet. Open an issue for that one as well here: https://github.com/zino-hofmann/graphql-flutter/issues/1349

**Comment by rrifafauzikomara** [comment]
Update.

Now i saw this on the log.

```dart
flutter: Initialising connection
flutter: Disconnected from websocket.
flutter: Initialising connection
flutter: Disconnected from websocket.
flutter: Initialising connection
```

Mean successfully connecting to subscription/websocket?

**Comment by rrifafauzikomara** [comment]
> you may are setting the wrong ws protocol?

so this one (https://github.com/zino-hofmann/graphql-flutter/issues/1350#issuecomment-1640470400) still not connected to subscription/websocket?

**Comment by vincenzopalazzo** [comment]
the ws has different protocols

**Comment by rrifafauzikomara** [comment]
> the ws has different protocols

hmm what u mean diff protocols? or do u have any idea what code should i check?

Coz basically, i just added this code.

```dart
final AuthLink authLink =
          AuthLink(getToken: () => 'Bearer $currentToken');

      final Link linkSplitted = authLink.split(
        (request) => request.isSubscription,
        webSocketLink,
        httpLink,
      );
```

and the result is this: https://github.com/zino-hofmann/graphql-flutter/issues/1350#issuecomment-1640470400

If I remove that like this one.

```dart
final Link linkSplitted = httpLink.split(
        (request) => request.isSubscription,
        webSocketLink,
        httpLink,
      );
```

I will got an error like this one: https://github.com/zino-hofmann/graphql-flutter/issues/1350#issue-1770000167

**Comment by vincenzopalazzo** [comment]
this https://github.com/zino-hofmann/graphql-flutter/pull/1206 should have a basic configuration of the ws, also please check the documentation and also research about grahql ws protocols

**Comment by rrifafauzikomara** [comment]
let me check ur `example`: https://github.com/zino-hofmann/graphql-flutter/tree/main/examples/starwars

idk why prev i dont see it.

**Comment by rrifafauzikomara** [comment]
Hi, @vincenzopalazzo @robertoestivill have a question.

In Postman, if I don't send a `Message` by clicked the `Send` button after successfully connected to the wss. I also can't get the data. The result is the same as this one (https://github.com/zino-hofmann/graphql-flutter/issues/1350#issuecomment-1640470400), only successfully connected or disconnected.

<img width="1032" alt="Screenshot 2023-07-19 at 1 05 14 AM" src="https://github.com/zino-hofmann/graphql-flutter/assets/26451363/4e80749e-efff-491c-94e2-271d0e0befd9">

So my question is, how can I send a `Message` from the app side using this package?
