### ISSUE TITLE
Null check operator used on a null value in SocketClient.onConnectionLost

### ISSUE THREAD

**Issue by vytautas-pranskunas-** [zino-hofmann/graphql-flutter#1379]
my error logger reports follwoing error:

```
_TypeError
 
websocket_client.dart in SocketClient.onConnectionLost

Ongoing
Level: Error
Null check operator used on a null value
```

```
websocket_client.dart in SocketClient.onConnectionLost at line 371 within graphql
In App
websocket_client.dart in SocketClient._connect at line 365 within graphql
```

**Comment by priyanshnama** [comment]
can i work on this

**Comment by WieFel** [comment]
I have the same problem on Android (API 34). It crashes even the whole emulator at app start.
On web, my code works fine.
```
E/flutter ( 4262): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Null check operator used on a null value
E/flutter ( 4262): #0      SocketClient.onConnectionLost (package:graphql/src/links/websocket_link/websocket_client.dart:375:29)
E/flutter ( 4262): #1      SocketClient._connect (package:graphql/src/links/websocket_link/websocket_client.dart:369:7)
E/flutter ( 4262): <asynchronous suspension>
```

My client initialisation code looks like this:
```dart
final errorLink = ErrorLink(
  onException: (request, forward, exception) {
    logger.e(exception);
    return null;
  },
);

final WebSocketLink websocketLink = WebSocketLink(
  websocketBackendUrl,
  config: SocketClientConfig(
      autoReconnect: true,
      inactivityTimeout: const Duration(seconds: 30),
      initialPayload: () async {
        // ... some authentication logic
      }),
  subProtocol: GraphQLProtocol.graphqlTransportWs,
);

Link link = errorLink.concat(websocketLink);

return GraphQLClient(
  link: link,
  cache: GraphQLCache(store: InMemoryStore()),
  defaultPolicies: DefaultPolicies(
    query: Policies(fetch: FetchPolicy.noCache),
    mutate: Policies(fetch: FetchPolicy.noCache),
  ),
);
```
