### ISSUE TITLE
JsonUnsupportedObjectError on file upload

### ISSUE THREAD

**Issue by Yunnigg** [zino-hofmann/graphql-flutter#871]
**Describe the issue**

When I try to upload a file as a `MultiPartFile` via a mutation the `QueryResult` contains a `LinkException` with `JsonUnsupportedObjectError`. 
The mutation is sent to the server perfectly fine and the file gets uploaded. 
The `data` Property is `null` in this case even when `ErrorPolicy.ignore` or `ErrorPolicy.all` is set.

Mutation:
```graphql
mutation addDeploymentPlan(
    $file: Upload!,
    $availableFrom: DateTime!,
    $availableUntil: DateTime!
  ) {
    addDeploymentPlan(
      file: $file,
      availableFrom: $availableFrom,
      availableUntil: $availableUntil
    ) {
      link
    }
  }
```

It seems the error occurs, when the graphql library tries to save the mutation to the cache, because when I deactivate the cache via a `FetchPolicy` the `QueryResult` doesn't contain any errors.

FetchPolicy:
```dart
final policies = Policies(
  fetch: FetchPolicy.noCache,
);

_graphQLClient = GraphQLClient(
  link: link,
  cache: GraphQLCache(),
  defaultPolicies: DefaultPolicies(
    watchQuery: policies,
    query: policies,
    mutate: policies,
  ),
);
```

**To Reproduce**

1. Implement the following mutation:
```dart
File pdfFile = ...
DateTime availableFrom = ...
DateTime availableUntil = ...

final multiPartFile = MultipartFile.fromBytes(
  'upload',
  pdfFile.readAsBytesSync(),
  filename: pdfFile.path,
  contentType: MediaType("application", "pdf"),
);

const createDeploymentPlan = """
  mutation addDeploymentPlan(
    \$file: Upload!,
    \$availableFrom: DateTime!,
    \$availableUntil: DateTime!
  ) {
    addDeploymentPlan(
      file: \$file,
      availableFrom: \$availableFrom,
      availableUntil: \$availableUntil
    ) {
      link
    }
  }
""";

final queryVariables = {
  "file": multiPartFile,
  "availableFrom": availableFrom.toIso8601String(),
  "availableUntil": availableUntil.toIso8601String(),
};

final mutationOptions = MutationOptions(
  document: gql(createDeploymentPlan),
  variables: queryVariables,
);

final queryResult = await _graphQLClient.mutate(mutationOptions);
```
2. Run flutter on Android or Web (iOS is most likely also affected but wasn't tested).
3. `queryResult` contains the error.

**Expected behavior**

The error shouldn't occur. The above mentioned workaround where I need to deactivate the cache is not sufficient, since I need the cache in my application.

**device / execution context**

- Platforms : 
  - Android (Physical Device)
  - Web (Google Chrome)
- Flutter 2.0.3:
  - graphql 4.0.0
  - http 0.12.2

### Other useful/optional fields

<details>
  <summary>Stacktrace:</summary>

```dart
#0      _JsonStringifier.writeObject (dart:convert/json.dart:688:7)
#1      _JsonStringifier.writeMap (dart:convert/json.dart:769:7)
#2      _JsonStringifier.writeJsonValue (dart:convert/json.dart:724:21)
#3      _JsonStringifier.writeObject (dart:convert/json.dart:679:9)
#4      _JsonStringStringifier.printOn (dart:convert/json.dart:877:17)
#5      _JsonStringStringifier.stringify (dart:convert/json.dart:862:5)
#6      JsonEncoder.convert (dart:convert/json.dart:262:30)
#7      JsonCodec.encode (dart:convert/json.dart:172:45)
#8      fieldNameWithArguments (package:normalize/src/utils/field_name_with_arguments.dart:64:27)
#9      normalize.normalizeNode (package:normalize/src/normalize.dart:94:11)
#10     normalize (package:normalize/src/normalize.dart:128:69)
#11     NormalizingDataProxy.writeQuery (package:graphql/src/cache/_normalizing_data_proxy.dart:94:5)
#12     QueryManager._resolveQueryOnNetwork (package:graphql/src/core/query_manager.dart:174:21)
<asynchronous suspension>
#13     QueryManager.mutate.<anonymous closure> (package:graphql/src/core/query_manager.dart)
<asynchronous suspension>
```

</details>

**screenshots**

LinkException:
![image](https://user-images.githubusercontent.com/12544936/115069793-634afe00-9ef4-11eb-9823-395c452d807f.png)

**Comment by lsaudon** [comment]
Use `import 'package:http/http.dart' show MultipartFile;` and not 'dio.dart` package
